# Generated by Django 4.1.9 on 2023-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('key', models.CharField(max_length=16)),
                ('payed', models.BooleanField()),
            ],
        ),
    ]
