# Generated by Django 4.1.9 on 2023-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
